# Docker Compose for Production - Use this file in Dockge
# This version builds from a local directory instead of Git
services:
  reading-buddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading-buddy
    image: reading-buddy:latest
    restart: unless-stopped

    ports:
      - "3000:3000"  # Change the first port if you want to expose on a different port

    environment:
      # Supabase Configuration
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

      # MinIO Configuration (Self-Hosted Storage)
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT:-443}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-true}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-reading-buddy}

      # Google AI Configuration
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      # Next.js Configuration
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - reading-buddy-network

networks:
  reading-buddy-network:
    driver: bridge
